// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActiveOnHeightController from "./active_on_height_controller"
application.register("active-on-height", ActiveOnHeightController)

import AddInputController from "./add_input_controller"
application.register("add-input", AddInputController)

import ArticleHighlightController from "./article_highlight_controller"
application.register("article-highlight", ArticleHighlightController)

import CharacterCounter from 'stimulus-character-counter'
application.register('character-counter', CharacterCounter)

import CheckboxListController from "./checkbox_list_controller"
application.register("checkbox-list", CheckboxListController)

import CssClassesController from "./css_classes_controller"
application.register("css-classes", CssClassesController)

import DisplayButtonOnHoverController from "./display_button_on_hover_controller"
application.register("display-button-on-hover", DisplayButtonOnHoverController)

import DisplayPhotoInputController from "./display_photo_input_controller"
application.register("display-photo-input", DisplayPhotoInputController)

import DuplicateInputsController from "./duplicate_inputs_controller"
application.register("duplicate-inputs", DuplicateInputsController)

import EventsScrollController from "./events_scroll_controller"
application.register("events-scroll", EventsScrollController)

import FilterCalendarController from "./filter_calendar_controller"
application.register("filter-calendar", FilterCalendarController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FullscreenElementController from "./fullscreen_element_controller"
application.register("fullscreen-element", FullscreenElementController)

import Map__Tileset__CreateController from "./map/tileset/create_controller"
application.register("map--tileset--create", Map__Tileset__CreateController)

import MapController from "./map_controller"
application.register("map", MapController)

import NavbarTogglerController from "./navbar_toggler_controller"
application.register("navbar-toggler", NavbarTogglerController)

import OverlayMenuController from "./overlay_menu_controller"
application.register("overlay-menu", OverlayMenuController)

import PhotoPreviewController from "./photo_preview_controller"
application.register("photo-preview", PhotoPreviewController)

import PhotoswipeController from "./photoswipe_controller"
application.register("photoswipe", PhotoswipeController)

import PublishCheckboxController from "./publish_checkbox_controller"
application.register("publish-checkbox", PublishCheckboxController)

import RevealOnClickController from "./reveal_on_click_controller"
application.register("reveal-on-click", RevealOnClickController)

import ScrollReveal from 'stimulus-scroll-reveal'
application.register('scroll-reveal', ScrollReveal)

import SlideNFadeLController from "./slide_n_fade_l_controller"
application.register("slide-n-fade-l", SlideNFadeLController)

import SlideNFadeRController from "./slide_n_fade_r_controller"
application.register("slide-n-fade-r", SlideNFadeRController)

import SweetalertController from "./sweetalert_controller"
application.register("sweetalert", SweetalertController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import SwiperCollaborators from "./swiper_collaborators_controller"
application.register("swiper-collaborators", SwiperCollaborators)

import SwiperSlideshowController from "./swiper_slideshow_controller"
application.register("swiper-slideshow", SwiperSlideshowController)

import ToGeojsonController from "./to_geojson_controller"
application.register("to-geojson", ToGeojsonController)

import ToggleElementController from "./toggle_element_controller"
application.register("toggle-element", ToggleElementController)

import ToggleOnChangeController from "./toggle_on_change_controller"
application.register("toggle-on-change", ToggleOnChangeController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import TomSelectCreateOptionController from "./tom_select_create_option_controller"
application.register("tom-select-create-option", TomSelectCreateOptionController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
