// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActiveOnHeightController from "./active_on_height_controller"
application.register("active-on-height", ActiveOnHeightController)

import ArticleHighlightController from "./article_highlight_controller"
application.register("article-highlight", ArticleHighlightController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import PhotoPreviewController from "./photo_preview_controller"
application.register("photo-preview", PhotoPreviewController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
